* Introduction
This repository contains the data and interactive Python (ipython)
script used the process and graph the data, using the Jupyter Notebook
tool.

One the Jupyter Notebook has been installed, it can be run using:
#+BEGIN_EXAMPLE
  jupyter-notebook
#+END_EXAMPLE

This will start a local server, and open a browser connecting to this
service, and display the contents of the local directory. Select the
appropriate workbook to continue. 

* Setup of the Jupyter Workbook
** Software Intallation
This software has been run on Ubuntu 17.10 

Download and install the Jupyter Notebook and it's dependancies.

*** (Old) Web documentation
The following documenation is old, but may still be useful: 
https://www.digitalocean.com/community/tutorials/how-to-set-up-a-jupyter-notebook-to-run-ipython-on-ubuntu-16-04

At one stage I needed to run the following:
#+BEGIN_SRC 
pip3 install --upgrade --force-reinstall --no-cache-dir jupyter
#+END_SRC

Instead of running 'jupiter workbook', use 'jupiter-workbook' instead. 
 
* Python Software
** Pandas
 
See Tutorials: https://pandas.pydata.org/pandas-docs/stable/tutorials.html

* Data sets
| filename                  |             start | date                          |               end | date                          |
|---------------------------+-------------------+-------------------------------+-------------------+-------------------------------|
| cosmic-array.log.20180116 | 1515142282.402535 | Fri  5 Jan 19:21:22 ACDT 2018 | 1516084500.385583 | Tue 16 Jan 17:05:00 ACDT 2018 |
| cosmic-array.log.20180217 | 1516084564.897229 | Tue 16 Jan 17:06:04 ACDT 2018 | 1518870464.984408 | Sat 17 Feb 22:57:44 ACDT 2018 |
| cosmic-array.log.20180402 | 1518870757.834977 | Sat 17 Feb 23:02:37 ACDT 2018 | 1522673001.725486 | Mon  2 Apr 22:13:21 ACST 2018 |
|---------------------------+-------------------+-------------------------------+-------------------+-------------------------------|
| cosmic-array.log.combined | 1515142282.402535 | Fri  5 Jan 19:21:22 ACDT 2018 | 1522673001.725486 | Mon  2 Apr 22:13:21 ACST 2018 |

* Tools/Scripts
The following are some examples on how to download data from a Cosmic
Array sensor.

#+BEGIN_EXAMPLE
# IP Address of Cosmic Array sensor.
CAHOST=10.147.20.58

# Rotate data
DATESTAMP=`date +"%Y%m%d"`
ssh pi@$CAHOST mv git/cosmic-array/cosmic-array.log git/cosmic-array.log.$DATESTAMP
ssh pi@$CAHOST reboot

# Get files
scp pi@$CAHOST:git/cosmic-array/cosmic-array.log.* .

# To get time from unix timestamp use:
date -d @1515142282

# Combine the files
cat cosmic-array.log.[0-9]* > cosmic-array.log.combined
#+END_EXAMPLE

